//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaVuelosAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Rut { get; set; }
        public string Numero_Pasaporte { get; set; }
        public string Direccion { get; set; }
        public int Numero_Direccion { get; set; }
        public int Numero_Telefono { get; set; }
        public string Nombres_Emergencia { get; set; }
        public string Apellidos_Emergencia { get; set; }
        public int Numero_Telefono_Emergencia { get; set; }
        public int ID { get; set; }
    }
}
