//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaVuelosAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int ID { get; set; }
        public string ID_Vuelo { get; set; }
        public string Ciudad_Origen { get; set; }
        public string Ciudad_Destino { get; set; }
        public System.DateTime Fecha_Salida { get; set; }
        public System.DateTime Fecha_Llegada { get; set; }
        public int Cupos { get; set; }
        public string Categoria { get; set; }
    }
}
