//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaVuelosAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Rut { get; set; }
        public int ID { get; set; }

        public Manager(string Nombres, string Apellidos, string Rut, int ID)
        {
            this.Nombres = Nombres;
            this.Apellidos = Apellidos;
            this.Rut = Rut;
            this.ID = ID;
        }

        public Manager()
        {

        }
    }
}
