//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaVuelosAPI.Models
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Clase parcial del modelo del Manager, contiene la declaracion de cada una de sus propiedades.
    /// ID es la clave primaria, es correlativa al ID del modelo Rol.
    /// </summary>
    public partial class Manager
    {
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Rut { get; set; }
        public int ID { get; set; }
    }
}
