//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaVuelosAPI.Models
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Clase parcial del modelo del Reserve, contiene la declaración de cada una de sus propiedades.
    /// ID es la clave primaria, es correlativa al ID del modelo Rol.
    /// ID_Flight corresponde al ID del modelo Flight.
    /// ID_Customer corresponde al ID del modelo Customer.
    /// </summary>
    public partial class Reserve
    {
        public int ID_Flight { get; set; }
        public int ID_Customer { get; set; }
        public int ID { get; set; }
    }
}
