//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaVuelosAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserve
    {
        public int ID_Flight { get; set; }
        public int ID_Customer { get; set; }
        public int ID { get; set; }

        public Reserve(int ID_Flight, int ID_Customer, int ID)
        {
            this.ID_Flight = ID_Flight;
            this.ID_Customer = ID_Customer;
            this.ID = ID;
        }

        public Reserve()
        {

        }
    }
}
