//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaVuelosAPI.Models
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Clase parcial del modelo del Rol, contiene la declaración de cada una de sus propiedades.
    /// ID es la clave primaria.
    /// ID_Rol es false cuando se trata de Customer y true cuando se trata de Manager.
    /// </summary>
    public partial class Rol
    {
        public string Email { get; set; }
        public string Contrasenia { get; set; }
        public bool ID_Rol { get; set; }
        public int ID { get; set; }
    }
}
